stages: 
  - deploy

deploy:
  stage: deploy
  only:
    - tags
  script:
    - export PATH=$PATH:/home/sbs/.nvm/versions/node/v12.14.1/bin
    - cp ~/extra_binary/ffmpeg.exe src/bin/ffmpeg.exe
    - yarn && yarn run package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - release/*.exe
      - release/*.yml
      - release/*.blockmap 
