stages: 
  - deploy

deploy:
  stage: deploy
  script:
    - export PATH=$PATH:/home/sbs/.nvm/versions/node/v12.14.1/bin
    - yarn && yarn run package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - release/*
